### PR TITLE
Added Platform to BuildOptions return of OptsFromBuildInfo

### LINKED ISSUE #3488: Can't build a Linux docker on a local M1 mac envirnoment
**Describe the bug**

I have a Kubernetes cluster which runs on Linux x86 OS/platform/container.
My local development environment is a Mac M1 laptop. I have a git repository of a helloworld Python web app with a helm chart (a simple k8s deployment) and a dockerfile.
I want to do development within the Kubernetes cluster via Okteto CLI.
I can use Okteto CLI to build a docker image on my laptop and push it to the docker hub register.
However, the image built by the Okteto CLI is of Darwin Arm platform, but I am expecting Linux x86 or Linux amd64.
I tried using the Okteto CLI “—platform” but it doesn’t work, the pushed image is still the same.
Example command: 
"okteto build --platform "linux/amd64" -l info”

I also tried adding a "platform" section in my Okteto build file, but it still doesn't change anything.

**Desktop (please complete the following information):**

- OS: macOS M1
- Okteto cli version of 2.13.0 (installed it from brew. 

**Additional context**

I also read https://github.com/okteto/okteto/issues/2921, but i'm not sure what's the correct fix, would appreciate someone shed the light here.

**Dockerfile**

```
ARG PY_VER=3.10
FROM ubuntu:22.04

RUN apt-get update && apt-get install -yq curl wget jq vim tldr silversearcher-ag tree xclip bat magic-wormhole net-tools

RUN echo `python -V`
```

**Okteto build file**

```
name: vision_app

# The build section defines how to build the images of your development environment
# More info: https://www.okteto.com/docs/reference/manifest/#build
build:
  training:
    context: .
    dockerfile: Dockerfile
    image: asiacao/vision-app
    platform: linux/amd64

deploy:
  - 'helm upgrade --install training chart'

dev:
  training:
    image: ${OKTETO_BUILD_TRAINING_IMAGE}
    command: bash
    workdir: /usr/src/app
    sync:
      - .:/usr/src/app
    environment:
      - name=$USER
```

### PR DESCRIPTION
**Pull request by teresaromero**
# Proposed changes

Fixes #3488 

- Add `o.Platform` to buildOptions to transmit this option into the build

## Test

- Default platform for my setup is "linux/arm64" when running `okteto build` this is the platform my images are made into

- using context without buildkit, using my local docker deamon and using dockerhub as registry

```
❯ ok build --platform "linux/amd64"
 i  Building 'Dockerfile' using your local docker daemon
....
 ✓  Image 'teresaromero/go-getting-started' successfully pushed
```
```
❯ docker image inspect teresaromero/go-getting-started:latest
[
    {
        "RepoTags": [
            "teresaromero/go-getting-started:latest"
        ],
    ...
        "Architecture": "amd64",
        "Os": "linux",
...
    }
]

```

- using cloud context, using buildkit for the build and using dockerhub as registry

```
❯ ok build --platform "linux/amd64"
 i  Building 'Dockerfile' in tcp://buildkit.cloud.okteto.net:443...
...
 ✓  Image 'teresaromero/go-getting-started' successfully pushed
```

```
❯ docker image inspect teresaromero/go-getting-started:latest
[
    {
        "RepoTags": [
            "teresaromero/go-getting-started:latest"
        ],
    ...
        "Architecture": "amd64",
        "Os": "linux",
...
    }
]

```

- using cloud context, using buildkit for the build and using external registry

```
❯ ok build -t <registry>/go-getting-started:latest --platform "linux/amd64"
 i  Building 'Dockerfile' in tcp://buildkit.cloud.okteto.net:443...
...
 ✓  Image '<registry>/go-getting-started:latest' successfully pushed
```

```
❯ docker run -it --rm <registry>/go-getting-started:latest
...
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

### CODE REVIEW

**Comment by ifbyol** [comment]
Have to tried to use any of those images in an environment where they cannot be used to verify they work or not as expected? I mean, for example, building an arm64 image but running it in some place where only amd64 is expected.

**Review by ifbyol — APPROVED** [review]

**Comment by AdrianPedriza** [comment]
LGTM!
just to clarify, so, using okteto to build the image, we were not sending the platform value to buildkit if the user indicated it?

**Review by AdrianPedriza — APPROVED** [review]

**Comment by teresaromero** [comment]
> LGTM! just to clarify, so, using okteto to build the image, we were not sending the platform value to buildkit if the user indicated it?

thats it

**Review by rberrelleza — COMMENTED** [review]
@teresaromero what is the value of Platform if the user doesn't specify it?

**Comment by ifbyol** [comment]
> > Have to tried to use any of those images in an environment where they cannot be used to verify they work or not as expected? I mean, for example, building an arm64 image but running it in some place where only amd64 is expected.
> 
> At the testing cases, the last one, the image was amd64 and the platform where run is arm64, did you mean that?

@teresaromero No, I mean if we actually tried to deploy those images and see if there work (or not) according to the image running and the platform where that image is running

**Pull request merged**
