### PR TITLE
Removed feature for automatically export/import the build cache

### LINKED ISSUE #3698: Disable automatic pull & export default cache
**Describe the bug**
Since Okteto CLI 2.15.0, there is logic to automatically pull &  export the buildkit cache.
Looking at the metrics, it didn't help to accelerate builds, and it even adding delays on average because of the extra time to import/export the cache.

**Expected behavior**
Remove the feature for automatically export/import the build cache, and let the user specify `export_to/import_from` as desired

### PR DESCRIPTION
**Pull request by AnshulAngaria**
Fixes #3698 

This PR adds changes to remove the automatic export/import build cache feature, as it was adding delays in the build.

### CODE REVIEW

**Comment by andreafalzetti** [comment]
Thanks @AnshulAngaria for raising this PR 🙏 

Could you check `cache_from.go`, I believe the type `oktetoRegistryInterface` is no longer used now.

**Review by andreafalzetti — APPROVED** [review]
Left a comment, otherwise LGTM.

Tested and it's working as expected

**Comment by AnshulAngaria** [comment]
> Thanks @AnshulAngaria for raising this PR 🙏
> 
> Could you check `cache_from.go`, I believe the type `oktetoRegistryInterface` is no longer used now.

@andreafalzetti Removed this interface.

**Comment by andreafalzetti** [comment]
Thanks @AnshulAngaria! Merging now :)

**Pull request merged**
