### PR TITLE
fix: remove duplicated text using `--insecure-skip-tls-verify` flag

### LINKED ISSUE #3885: When I execute `okteto ctx` command with --insecure-skip-tls-verify flag, the `Insecure mode enabled` message is displayed twice
**Describe the bug**

When I execute `okteto ctx` with `--insecure-skip-tls-verify` flag, a warning message `! Insecure mode enabled` is displayed twice

Captura de pantalla 2023-08-04 a las 18 45 10

**To Reproduce**

1. Execute `okteto ctx use https://cloud.okteto.com --insecure-skip-tls-verify`

**Expected behavior**

The warning message is displayed only once

**Desktop (please complete the following information):**

Checking with different versions it seems that started to happen in `2.17.x` version

**Additional context**
Add any other context about the problem here (e.g. okteto.yml, k8s manifests, logs)

### PR DESCRIPTION
**Pull request by nitishfy**
# Proposed changes

Fixes #3885

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

## How to validate

Please provide step-by-step instructions to replicate your validation scenario. For bug fixes, detail how to reproduce both the bug and its fix, along with any observations.

1. Reference: https://github.com/okteto/okteto/issues/3885#issuecomment-1729958156
image

## CLI Quality Reminders 🔧

For both authors and reviewers:

- Scrutinize for potential regressions
- Ensure key automated tests are in place
- Build the CLI and test using the validation steps
- Assess Developer Experience impact (log messages, performances, etc)
- If too broad, consider breaking into smaller PRs
- Adhere to our [code style](https://github.com/okteto/okteto/blob/master/docs/code-style.md) and [code review](https://github.com/okteto/okteto/blob/master/docs/code-review.md) guidelines

**Please Note that this is a Draft Pull Request raised to bring a minimal solution to the issue. Open to suggestions to find better way of fixing this issue.**

### CODE REVIEW

**Comment by jLopezbarb** [comment]
Hey @nitishfy. This one is little more complicated. I recommend you taking a look to https://github.com/okteto/okteto/pull/3981 since the issue was quite similar. Let me know if you have any problem

**Comment by andreafalzetti** [comment]
Hi @nitishfy - is this ready to review?

**Comment by nitishfy** [comment]
> Hi @nitishfy - is this ready to review?

Umm, the changes are working as we want. However, with @jLopezbarb suggestion above, we might need a different approach to solve this problem. What's your thoughts?

(I'd still open this PR ready for review so that we can continue the discussion over here.)

**Comment by andreafalzetti** [comment]
@nitishfy I've just reviewed this issue/PR and I think being the change bigger than expected in the original issue, a propr fix will require a refactoring, so it's better if the ownership of such change is done by the CLI team so that we can be own it and be accountable for it. Also, it would require refactoring to make the change testable.

 I am closing this PR for now, thanks for your understanding and apologies for the confusion on our side.

**Pull request closed without merging**
