### PR TITLE
Fix okteto test logs

### PR DESCRIPTION
**Pull request by jLopezbarb**
# Proposed changes

Fixes DEV-357

- Successful execution:

Screenshot 2024-05-23 at 12 07 23

- Tests are cached. I think the message should be more like a normal print on white to distinct it with the other messages. WDYT @codyjlandstrom @pchico83? :

Screenshot 2024-05-23 at 12 07 48

- Failed execution

Screenshot 2024-05-23 at 12 25 34

- Spinner executing tests:

Screenshot 2024-05-23 at 12 28 56

- Large context:

Screenshot 2024-05-23 at 12 29 43

## How to validate

1. With the following manifest:
```yaml
deploy:
  - echo hello
test:
  backend:
    image: okteto/golang:1
    context: .
    commands:
      - name: command1
        command: echo "this is command 1"
      - name: command2
        command: echo "this is command 2"
```
2. Run `okteto test` several times, one for running it and another one for the cache
3. Modify one of the test command to have a failure and check the output
4. Modify one of the commands to be sleep 5000 to check the spinner
5. Create a big file using dd (`dd if=/dev/zero of=bigfile bs=1M count=1000`). After executing tests remember to delete it

## CLI Quality Reminders 🔧

For both authors and reviewers:

- Scrutinize for potential regressions
- Ensure key automated tests are in place
- Build the CLI and test using the validation steps
- Assess Developer Experience impact (log messages, performances, etc)
- If too broad, consider breaking into smaller PRs
- Adhere to our [code style](https://github.com/okteto/okteto/blob/master/docs/code-style.md) and [code review](https://github.com/okteto/okteto/blob/master/docs/code-review.md) guidelines

### CODE REVIEW

**Comment by pchico83** [comment]
@jLopezbarb I would do the following changes:
- "successfully executed" -> "passed"
- The first info (blue) message should be "Executing test container 'backend'", instead of "Executing backend"
- Then, for each command, an info (blue) message saying "Running 'command1'"
- The info message saying "Running stage 'backend'" can be removed

**Comment by pchico83** [comment]
@jLopezbarb what's the output of `okteto test` if the manifest doesn't have a `test` section?

**Comment by jLopezbarb** [comment]
> @jLopezbarb what's the output of `okteto test` if the manifest doesn't have a `test` section?

Right now there is a message saying there is no test section and we fail. We are changing that [in this PR](https://github.com/okteto/okteto/pull/4312) to show an information message and not fail.

cc: @andreafalzetti

**Comment by jLopezbarb** [comment]
> @jLopezbarb I would do the following changes:
> 
> * "successfully executed" -> "passed"
> * The first info (blue) message should be "Executing test container 'backend'", instead of "Executing backend"
> * Then, for each command, an info (blue) message saying "Running 'command1'"
> * The info message saying "Running stage 'backend'" can be removed

As we spoke offline the only change that could not be made is having the information message in blue due to a limitation in our remote log system. Here is an screenshot with the updated logs:
Screenshot 2024-05-23 at 13 53 24

**Comment by jLopezbarb** [comment]
> @jLopezbarb I think this PR has unrelated changes from https://okteto.atlassian.net/browse/DEV-232

I made a mistake when creating the branch and started it from the other one. I have changed the base branch to isolate the changes of this PR. Sorry for the inconvenience

**Review by ifbyol — APPROVED** [review]

**Comment by jLopezbarb** [comment]
Closing in favour of https://github.com/okteto/okteto/pull/4325

**Pull request closed without merging**
