### PR TITLE
add implementation to retrieve cmap variables when running in remote

### LINKED ISSUE #3735: `okteto deploy --remote` doesn't mask variables specified with `--var`
**Describe the bug**
Run `okteto deploy --remote --var TEST=111` with a deploy command `echo $TEST`.
The variable value isn't masked

**Expected behavior**
The variable is masked as any other variable/secret

### PR DESCRIPTION
**Pull request by AdrianPedriza**
# Context

when a variable is printed in deploy section using remote deploy feature it is not masked as expected. This is because implementation related to retrieve variables from config map in remote deploy mode is empty

Fixes #3735

# Proposed changes
- add implementation about retrieve variables from configmap when deploy is running remotely

# How to check the fix

1. Using latest CLI release
2. clone https://github.com/okteto/movies
3. set deploy section as:
````yaml
deploy:
  - name: test
    command: echo $TEST
````
4. run `okteto deploy --remote --var TEST=111`
5. Value should be masked

### CODE REVIEW

**Comment by pchico83** [comment]
@AdrianPedriza is it possible to add a test that covers this scenario? does the fix work for `okteto destroy --remote` too?

**Comment by AdrianPedriza** [comment]
> @AdrianPedriza is it possible to add a test that covers this scenario? does the fix work for `okteto destroy --remote` too?

I can add e2e test for it. On the other hand, `okteto destroy` doesn't accept variables so I'm afraid we can't cover that case for the destroy command

**Comment by pchico83** [comment]
> @AdrianPedriza is it possible to add a test that covers this scenario? does the fix work for `okteto destroy --remote` too?

@AdrianPedriza `okteto destroy --remote` reuses the variables used at deployment time. I want to test if those envvars are masked at destroy time, even if they were added with the `--var` option.

**Comment by AdrianPedriza** [comment]
> > @AdrianPedriza is it possible to add a test that covers this scenario? does the fix work for `okteto destroy --remote` too?
> 
> @AdrianPedriza `okteto destroy --remote` reuses the variables used at deployment time. I want to test if those envvars are masked at destroy time, even if they were added with the `--var` option.

👍 I will check that case for `destroy` command then. I will add an e2e test covering both cases

**Review by jLopezbarb — APPROVED** [review]

**Review by teresaromero — APPROVED** [review]
👍🏻

**Pull request merged**
