### PR TITLE
Copy okteto to system32 so its in path

### PR DESCRIPTION
**Pull request by AgustinRamiroDiaz**
# Proposed changes

Fixes https://github.com/okteto/platform-resources/issues/6

Fixes e2e tests:
- add okteto to path for windows
- uses custom builder for the binary (golang 1.18)
  - I was having issues in windows if the binary was being built with other golang versions.  
- upgraded golang text package (non necessary, but was part of the tests)
- improved error wrapping (non necessary, but was part of the tests)

### CODE REVIEW

**Comment by AgustinRamiroDiaz** [comment]
Researching:
- https://github.com/golang/go/issues/41425
- https://github.com/golang/go/issues/3575

**Comment by AgustinRamiroDiaz** [comment]
created https://github.com/okteto/okteto/pull/3558 to test in linux

**Comment by AgustinRamiroDiaz** [comment]
Tests keep failing:
- Tried different combinations of interfaces to get the port like `::1, :0`
- When connecting though SSH into the remote circleci job:
  - I can run thousands of time `net.ListenTCP` and it does not error
  - Git cloning movies or go-getting started + okteto deploy fails exactly the same as the e2e tests
  
  
I'll be now setting up my dev env in windows to see if I can repro locally

**Comment by AgustinRamiroDiaz** [comment]
@okteto/cli can I get some :eyes: on this? It's not going directly to main, but will ease out reviewing

**Review by jLopezbarb — APPROVED** [review]

**Comment by jLopezbarb** [comment]
I know it's not related with this PR but I don't have any other PR to publish the message. What's the fail message that we send the user when the okteto is not in PATH. I think the user should get a proper error on why is failing to connect to the cluster.

**Comment by AgustinRamiroDiaz** [comment]
@jLopezbarb you get a mix of the logs from kubectl and the install hint
```
$ k get pod
E0508 19:28:26.475016   74252 memcache.go:265] couldn't get current server API group list: Get "https://146.148.56.200:443/api?timeout=32s": getting credentials: exec: executable okteto not found

It looks like you are trying to use a client-go credential plugin that is not installed.

To learn more about this feature, consult the documentation available at:
      https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins

Okteto needs to be installed and in your PATH to use this context. Please visit https://www.okteto.com/docs/getting-started/ for more information.
```
(you get this error 3 times because the auth plugin has 3 retires for the command)

**Comment by jLopezbarb** [comment]
> @jLopezbarb you get a mix of the logs from kubectl and the install hint
> 
> ```
> $ k get pod
> E0508 19:28:26.475016   74252 memcache.go:265] couldn't get current server API group list: Get "https://146.148.56.200:443/api?timeout=32s": getting credentials: exec: executable okteto not found
> 
> It looks like you are trying to use a client-go credential plugin that is not installed.
> 
> To learn more about this feature, consult the documentation available at:
>       https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins
> 
> Okteto needs to be installed and in your PATH to use this context. Please visit https://www.okteto.com/docs/getting-started/ for more information.
> ```
> 
> (you get this error 3 times because the auth plugin has 3 retires for the command)

Thanks @AgustinRamiroDiaz 👍

**Pull request merged**
