### PR TITLE
fix antipatterns deepsource

### PR DESCRIPTION
**Pull request by jLopezbarb**
# Proposed changes

this PR addresses fixes for anti patterns issues at Deepsource master analysis.
https://deepsource.io/gh/okteto/okteto/issues?category=antipattern&page=1

### CODE REVIEW

**Review by AgustinRamiroDiaz — APPROVED** [review]

**Review by teresaromero — APPROVED** [review]

**Review by AdrianPedriza — APPROVED** [review]

**Comment by teresaromero** [comment]
@AgustinRamiroDiaz why did you merge this PR?

**Comment by AgustinRamiroDiaz** [comment]
> @AgustinRamiroDiaz why did you merge this PR? 

Yes. Is there a problem?

**Comment by AgustinRamiroDiaz** [comment]
> @AgustinRamiroDiaz why did you merge this PR? 

Because it had 3 approvals and they were internal changes. Do you want me to revert it?

**Comment by teresaromero** [comment]
> > @AgustinRamiroDiaz why did you merge this PR?
> 
> Because it had 3 approvals and they were internal changes. Do you want me to revert it?

There is no need to revert.
I was curious,  i expect that PRs are be merged by the person who opens them and have the option to delegate the merge in case of urgent situations or explicit delegation, which i am guessing is not the case. But this is just my point of view.

**Comment by AgustinRamiroDiaz** [comment]
> I was curious,  i expect that PRs are be merged by the person who opens them and have the option to delegate the merge in case of urgent situations or explicit delegation, which i am guessing is not the case. But this is just my point of view.

I think it's great to share this curiosities/concerns so that we are all in the same page, it will create smoother and healthier workflows ❤️

I like the approach you suggested. I'll write it out in the contribution guides!

**Comment by ifbyol** [comment]
> > I was curious,  i expect that PRs are be merged by the person who opens them and have the option to delegate the merge in case of urgent situations or explicit delegation, which i am guessing is not the case. But this is just my point of view.
> 
> I think it's great to share this curiosities/concerns so that we are all in the same page, it will create smoother and healthier workflows ❤️
> 
> I like the approach you suggested. I'll write it out in the contribution guides!

The PR owner is the one knowing the real state of the PR. A PR with several approves doesn't mean that it was fully tested by the owner.

This doesn't only apply to this repo, it also applies for the rest of our repos and it should be part of our workflow

**Pull request merged**
