### PR TITLE
Build with context

### LINKED ISSUE #2022: Support `--context` flag in any okteto command that supports `--namespace`
**Is your feature request related to a problem? Please describe.**
I want to run an okteto comman in a different context than my current okteto context.

**Describe the solution you'd like**
Have to uption to run `okteto up --context staging` if I want to run my okteto command in a particular context

### LINKED ISSUE #2500: Support to deploy a subset of docker compose services in the okteto manifest
**Is your feature request related to a problem? Please describe.**
My okteto manifest looks like this:
```
deploy:
   compose: docker-compose.yml
...
``` 
but I need to deploy only a subset of services
 
**Describe the solution you'd like**
Something like this:
```
deploy:
   compose:
      file: docker-compose.yml
      services:
        - a
        - b
...

### PR DESCRIPTION
**Pull request by AgustinRamiroDiaz**
Signed-off-by: Agustin Ramiro Diaz <agustin.ramiro.diaz@gmail.com>

Fixes #2022

## Proposed changes

- Add `--context` flag for build command
- Switch context based on the flag passed

### CODE REVIEW

**Comment by rberrelleza** [comment]
I think It's kind of confusing to have the --context, when we already have a command that sets the context for you. IF we are doing this, can we add it as a global parameter that affects all command (e.g. kind of like the --namespace or --kubeconfig parameters in kubectl)

okteto --context foo build

**Comment by pchico83** [comment]
> I think It's kind of confusing to have the --context, when we already have a command that sets the context for you. Specially if it's only for a few commands. If we are doing this, can we add it as a global parameter that affects all commands (e.g. kind of like the --namespace or --kubeconfig parameters in kubectl)
> 
> okteto --context foo build okteto --context foo up okteto --conext foo deploy

+1 for the global parameter. We could do it for `--context` and `--namespace`.

**Comment by AgustinRamiroDiaz** [comment]
@pchico83 @rberrelleza @rlamana That sounds great! 

I think this is a blocker for the docker extension. Should we use this that is working and open another issue to move it as root parameters?

**Comment by pchico83** [comment]
@AgustinRamiroDiaz yes, let's do that

**Review by pchico83 — APPROVED** [review]

**Pull request merged**
