### PR TITLE
Upgrade-buildkit-version-to-v0.10.3-okteto2

### LINKED ISSUE #2966: Upgrade buildkit version to `v0.10.3-okteto1`
**Is your feature request related to a problem? Please describe.**
We already have the new version working in cloud

**Describe the solution you'd like**
We should resolve all the package conflicts and test that the client is working correctly

**Additional context**
https://github.com/okteto/buildkit/releases/tag/v0.10.3-okteto1
[PR](https://github.com/okteto/okteto/pull/2987)

### PR DESCRIPTION
**Pull request by AgustinRamiroDiaz**
Fixes #2966

## Proposed changes

- Update imports
- Update function depending on updated module

As the pr is now, we are using the `master` version of `docker/docker` and `docker/cli`. We'll wait until they have a new release to update and merge this.

TODO:
- [ ] remove as much `replace` as possible
- [ ] change `master` versions for stable releases
- [ ] try to upgrade packages

### CODE REVIEW

**Comment by ifbyol** [comment]
Why we need to use the master version? Does it contain any fix that wasn't released yet?

**Comment by jLopezbarb** [comment]
yes, we have incompatibilities between [docker/libnetwork](https://github.com/docker/libnetwork) and [docker/docker](https://github.com/moby/moby). They will remove `libnetwork` dependency on the next release, so we need to either use `master` until they release a new version or wait until they release the new version.

If we don't wait I think we'd need to add some comments explaining why we are pinning to `master` and what should be done in order to unpin those dependencies

**Comment by jLopezbarb** [comment]
We're still waiting for [docker/docker](https://github.com/moby/moby) to release a new patch

**Comment by AdrianPedriza** [comment]
> We're still waiting for [docker/docker](https://github.com/moby/moby) to release a new patch

there is a new release. We should point to `v0.10.3-okteto2` instead of `v0.10.3-okteto1`

**Comment by AgustinRamiroDiaz** [comment]
I've [created an issue](https://github.com/moby/moby/issues/44056) in docker/docker to see if they can tell us an approximate date for the next patch release

**Comment by jLopezbarb** [comment]
@AgustinRamiroDiaz you should check deepsource issues. It seems that with your changes we are using deprecated functions. Can we update them to use the new ones?

**Comment by jLopezbarb** [comment]
@AgustinRamiroDiaz there is [a new buildkit release 0.10.4](https://github.com/moby/buildkit/releases/tag/v0.10.4) and [a new docker/docker release](https://github.com/moby/moby/releases/tag/v20.10.18) which seems to fix several security issues. Can you try using those new versions?

**Comment by AgustinRamiroDiaz** [comment]
I wasn't able to improve this with the new docker/docker release. I come with the same old errors with `Sirupsen` and `libnetwork`

**Comment by AgustinRamiroDiaz** [comment]
> @AgustinRamiroDiaz There is a [new buildkit release 0.10.5](https://github.com/moby/buildkit/releases/tag/v0.10.5) and a new [docker cli](https://github.com/moby/moby/releases/tag/v20.10.20) that patches some security issues. Can you check if you can upgrade them?

@jLopezbarb still couldn't make it work. An alternative I'm thinking about could be to vendor libnetwork in this repo until they release without that dependency. WDYT?

**Pull request closed without merging**
