### PR TITLE
add e2e test to check if build cmd replace secrets properly

### LINKED ISSUE #3056: Add e2e for build cmd to check secrets are resolved properly
**Is your feature request related to a problem? Please describe.**
we should add an e2e test to cover the case of checking that the secrets are correctly added when reading the manifest for the `okteto build` command.  In order to release [the fix](#3051 ) that solves #3044, the suggestion for the addition a e2e test is made separately of the original PR.

### PR DESCRIPTION
**Pull request by AdrianPedriza**
Signed-off-by: adripedriza <adripedriza@gmail.com>

# Proposed changes

Fixes #3056

- add e2e test where build cmd is tested using secrets in manifest build section

### CODE REVIEW

**Comment by AgustinRamiroDiaz** [comment]
Does this test need `RABBITMQ_PASS` to be set from the UI? 
If it does:
- Is there a way to create the secret from the CLI?
- Can we document it?

**Comment by AdrianPedriza** [comment]
> Does this test need `RABBITMQ_PASS` to be set as a secret from the UI? If it does:
> 
> * Is there a way to create the secret from the CLI? Maybe we need to create another issue for this
> * Can we document it?

It is already added as a secret. For the moment we cannot add secrets in the test itself by using the CLI but there is already an issue  to create test from CLI. https://github.com/okteto/okteto/issues/3006

**Comment by AgustinRamiroDiaz** [comment]
@AdrianPedriza so we'd need to add the steps to set `RABBITMQ_PASS` [here](https://github.com/okteto/okteto/blob/master/docs/how-to-run-tests.md)

**Comment by AdrianPedriza** [comment]
> @AdrianPedriza so we'd need to add the steps to set `RABBITMQ_PASS` [here](https://github.com/okteto/okteto/blob/master/docs/how-to-run-tests.md)

There is no need to set it, it is already set for that environment. Anyway, I know at the moment it is coupled to the secrets you have in that environment but once you can add secrets from the CLI it will be more dynamic. I will add a reminder in the [issue](https://github.com/okteto/okteto/issues/3006) to take into account tests like this.

**Comment by jLopezbarb** [comment]
Can we run e2e tests before approving it? I want to make sure it's passing

**Comment by AdrianPedriza** [comment]
> Can we run e2e tests before approving it? I want to make sure it's passing

passed! @jLopezbarb

**Review by jLopezbarb — APPROVED** [review]

**Pull request merged**
