### PR TITLE
don't initialize okteto client if not using okteto cloud

### PR DESCRIPTION
**Pull request by etrombly**
# Proposed changes

Fixes # 3401

Tested to work on a local k8s cluster, I don't have an okteto cloud account setup, but shouldn't impact it.

### CODE REVIEW

**Review by jLopezbarb — APPROVED** [review]

**Comment by jLopezbarb** [comment]
Hi @etrombly, Changes looks good. I've send you an invitation to Okteto cloud to allow you to test the PR. Let me know if you can't access or have any problem

**Comment by etrombly** [comment]
It wouldn't let me respond on the review:

I'm still setting name from options.Name, I just do it under the block that checks if options.Name is empty and initializes it. I was running into it being empty.

Honestly we probably don't even need the name variable and could just use options.Name directly.

**Comment by jLopezbarb** [comment]
> I'm still setting name from options.Name, I just do it under the block that checks if options.Name is empty and initializes it. I was running into it being empty in the notification that the dev environment was deleted.

Yes, but it's modifying the `options.Name` which is needed later on and need to check if the `options.Name` is set or not. With the change you are proposing it'll always be set.

> If options.Name shouldn't be changed, then I need to see where the deletion notification is being set from, and have that use the name variable instead of options.Name.

Which delete notification? Maybe we can include another struct in the command to achieve that, but I want to understand the reason on changing the `options.Name` to be always set

**Comment by etrombly** [comment]
> Which delete notification? Maybe we can include another struct in the command to achieve that, but I want to understand the reason on changing the `options.Name` to be always set

The output of `okteto destroy` looks like this without the change:

```
 i  Using eric-trombly @ dev/eric.trombly@XXXX as context
 ✓  Development environment '' successfully destroyed
```

**Comment by jLopezbarb** [comment]
Let's do it in a separate issue. We'll need to check which implications it has before making the change. WDYT?

**Comment by etrombly** [comment]
Sounds good, I reverted the change to options.Name and will open a new issue

> Hi @etrombly, Changes looks good. I've send you an invitation to Okteto cloud to allow you to test the PR. Let me know if you can't access or have any problem

I haven't received the invitation. It may be my work spam filter, can you try sending it to etrombly@gmail.com?

**Review by AgustinRamiroDiaz — APPROVED** [review]

**Comment by jLopezbarb** [comment]
> Sounds good, I reverted the change to options.Name and will open a new issue
> 
> > Hi @etrombly, Changes looks good. I've send you an invitation to Okteto cloud to allow you to test the PR. Let me know if you can't access or have any problem
> 
> I haven't received the invitation. It may be my work spam filter, can you try sending it to [etrombly@gmail.com](mailto:etrombly@gmail.com)?

Can you try to login into cloud with this GH account. You should be able to login with it

**Comment by etrombly** [comment]
Looks like it's working properly in okteto cloud as well:
```
 eric > ~ > git > rust-getting-started > master > $ > /home/eric/git/okteto/bin/okteto destroy
 i  Using etrombly @ cloud.okteto.com as context
 ✓  Development environment '' successfully destroyed
 ```

**Review by jLopezbarb — APPROVED** [review]

**Comment by jLopezbarb** [comment]
Thanks @etrombly. This is a very nice addition!! It'll be ready for the next release

**Pull request merged**
