### PR TITLE
feat: execute destroy on remote if branch or repo options

### LINKED ISSUE #2449: Support `okteto destroy` `--repository` and `--branch` flags
**Is your feature request related to a problem? Please describe.**
If `--repository` or `--branch` flags are specified, the destroy is executed on remote (the equivalent to `okteto pipeline destroy`.

### PR DESCRIPTION
**Pull request by jLopezbarb**
Signed-off-by: Javier López Barba <javier@okteto.com>

Fixes #2449

## Proposed changes
- If okteto destroy command has branch or repository flags execute it on remote
-

### CODE REVIEW

**Comment by rberrelleza** [comment]
Have we considered a --remote option or something like that? 

I don't think that is going to be obvious for the user that passing the branch means that it'll run on cloud vs local

**Comment by pchico83** [comment]
@rberrelleza I also agree the current experience is confusing, although I don't have a clear alternative.
I would merge this one to have feature parity with `okteto deploy` while we have a better solution

**Comment by pchico83** [comment]
> @pchico83 With regards to parity, I think we should do opposite of what you suggest and instead remove the --branch and --repo from deploy instead, since it seems like everyone in this thread agrees that's not the right way to do this. We can let "okteto pipeline deploy/destroy" live a bit longer without a deprecation message for now?

@rberrelleza SGTM

**Comment by jLopezbarb** [comment]
Closing in favour of  https://github.com/okteto/okteto/pull/2477

**Pull request closed without merging**
