### PR TITLE
Improve tty output

### LINKED ISSUE #1985: Improve the output of `okteto deploy`
**Is your feature request related to a problem? Please describe.**
When I deploy a repo, I get plain output of what's going on. Same for deploying pipelines or previews.

**Describe the solution you'd like**
I would like to get output in a more structure way. For example, collapse the output of each command after execution. Then, show a list of my deployments and their state until they are successfully running. Something similar to the experience in the Okteto UI.

### PR DESCRIPTION
**Pull request by jLopezbarb**
Signed-off-by: Javier López Barba <javier@okteto.com>

Fixes #1985

## Proposed changes
- Refactor executor 
- Support tty execution

## Demos

Correct deployment:

https://user-images.githubusercontent.com/25170843/151397059-3bdc913f-d840-43cd-84ab-4df3ebfe2610.mov

Failed one:

https://user-images.githubusercontent.com/25170843/151396790-a4e71449-4604-4e9d-9da6-089bcd7fec91.mov

### CODE REVIEW

**Comment by pchico83** [comment]
@jLopezbarb would it be possible to show buildkit output on tty?
also, I would show like a normal log the `information` message about where the build is running, and keep colours just for the command is running.
@rlamana any feedback?

**Comment by rlamana** [comment]
@jLopezbarb Like discussed offline, can we indent the output of the command that is running? when okteto lunches another okteto command, the info messages look like part of the main `okteto deploy` command and it's a bit confusing

**Comment by jLopezbarb** [comment]
Quick update:
- When ctrl+C we were showing no output to the user, but the proxy and the goroutine for writing needed to be closed before exiting the program. Solution: Added a new spinner for the shutting down sequence
- Buildkit is now available on tty mode. Demo below
- Commands executed are being indented so we know that is not part of the main program.

## DEMOS

Correct output
https://user-images.githubusercontent.com/25170843/151798789-18476a96-82af-4a0f-af33-887f8eace9e7.mov

Ctrl+C sequence
https://user-images.githubusercontent.com/25170843/151798911-7080105e-1076-45d8-afe1-68459b6b9801.mov

**Comment by jLopezbarb** [comment]
Needs #2179 to include the output on the configmap to show a correct output on the UI

**Comment by rlamana** [comment]
Looking great! Just a few alignment issues:

1. Indentation should be properly aligned with the message icon:
Screenshot 2022-01-31 at 16 46 30

2. Spinner sometimes is properly centered and sometimes is not:
Screenshot 2022-01-31 at 16 41 28

**Comment by jLopezbarb** [comment]
> Looking great! Just a few alignment issues:
> 
> 1. Indentation should be properly aligned with the message icon:
> 
> Screenshot 2022-01-31 at 16 46 30
> 
> 2. Spinner sometimes is properly centered and sometimes is not:
> 
> Screenshot 2022-01-31 at 16 41 28


Agree on number 1 but number 2 is because closing the proxy and the tty output takes some time and I didn't want the user to think that was stuck, so I added a spinner saying that it's running the shutdown sequence (It's triggered when a interrupt signal, Ctrl+C). Probably the text is not the best, Maybe `Waiting for the shutdown sequence to finish...` is a better option What do you think?

**Comment by pchico83** [comment]
> > Looking great! Just a few alignment issues:
> > 
> > 1. Indentation should be properly aligned with the message icon:
> > 
> > Screenshot 2022-01-31 at 16 46 30
> > 
> > 2. Spinner sometimes is properly centered and sometimes is not:
> > 
> > Screenshot 2022-01-31 at 16 41 28
> 
> Agree on number 1 but number 2 is because closing the proxy and the tty output takes some time and I didn't want the user to think that was stuck, so I added a spinner saying that it's running the shutdown sequence (It's triggered when a interrupt signal, Ctrl+C). Probably the text is not the best, Maybe `Waiting for the shutdown sequence to finish...` is a better option What do you think?

@jLopezbarb what would be the issue if we don't wait for a clean shutdown (more than updating the configmap)?

**Comment by jLopezbarb** [comment]
> > > Looking great! Just a few alignment issues:
> > > 
> > > 1. Indentation should be properly aligned with the message icon:
> > > 
> > > Screenshot 2022-01-31 at 16 46 30
> > > 
> > > 2. Spinner sometimes is properly centered and sometimes is not:
> > > 
> > > Screenshot 2022-01-31 at 16 41 28
> > 
> > 
> > Agree on number 1 but number 2 is because closing the proxy and the tty output takes some time and I didn't want the user to think that was stuck, so I added a spinner saying that it's running the shutdown sequence (It's triggered when a interrupt signal, Ctrl+C). Probably the text is not the best, Maybe `Waiting for the shutdown sequence to finish...` is a better option What do you think?
> 
> @jLopezbarb what would be the issue if we don't wait for a clean shutdown (more than updating the configmap)?

Mostly updating the configmap. I was thinking about what could happen with the proxy (could it be blocking the port after the execution?) but after some tests, it's being closed correctly without any port being left

**Comment by rlamana** [comment]
@jLopezbarb ok, but can't we just use a spinner with the same "size" as the rest?

**Review by pchico83 — APPROVED** [review]

**Pull request merged**
