### PR TITLE
add deprecation notice for static tokens

### PR DESCRIPTION
**Pull request by AdrianPedriza**
Fixes #[6887 ](https://github.com/okteto/app/issues/6887)

- add deprecation notice and info about the change pointing to k8s docs

### CODE REVIEW

**Comment by AdrianPedriza** [comment]
add deprecation notes to CLI needs to be a task for the release containing full dynamic tokens feature so not addressing it in this PR

**Comment by AdrianPedriza** [comment]
discussint it offline with @andreafalzetti , we think that a refer to our docs explaining the change would be great instead of point directly to k8s docs. @rlamana should we include a task to create docs about use of dynamic tokens and point to that doc in the deprecation notice? (we need to add docs about feature flag to use static token until removal so we could take the opportunity)

**Comment by rlamana** [comment]
@AdrianPedriza, @andreafalzetti pointed out this issue (https://github.com/okteto/app/issues/6890) as the one covering the docs for this feature

**Comment by AdrianPedriza** [comment]
> @AdrianPedriza, @andreafalzetti pointed out this issue ([okteto/app#6890](https://github.com/okteto/app/issues/6890)) as the one covering the docs for this feature

I will close this issue and update ([okteto/app#6890](https://github.com/okteto/app/issues/6890)) and warning message once https://github.com/okteto/docs/pull/474 is merged

**Pull request closed without merging**
