### PR TITLE
Modified the spinner text to mention about destroying dev env

### PR DESCRIPTION
**Pull request by NitishKumar06**
Fixes:#3572

### CODE REVIEW

**Review by pchico83 — APPROVED** [review]
Thanks @NitishKumar06 !

**Comment by AdrianPedriza** [comment]
I believe that this PR is not correct. The problem is that we were not distinguishing between deploy and destroy in the message when displaying the spinner. If previously we always showed the `Deploying` message... now we only show the `Destroying..` message. You can check it running `okteto deploy --remote`. I will reopen the issue again

**Comment by pchico83** [comment]
> I believe that this PR is not correct. The problem is that we were not distinguishing between deploy and destroy in the message when displaying the spinner. If previously we always showed the `Deploying` message... now we only show the `Destroying..` message. You can check it running `okteto deploy --remote`. I will reopen the issue again

@NitishKumar06 my bad, we should show "Deploying..." on `okteto deploy` and "Dstroying..." on `okteto destroy`

**Comment by jLopezbarb** [comment]
> > @NitishKumar06 my bad, we should show "Deploying..." on `okteto deploy` and "Dstroying..." on `okteto destroy`
> 
> I'm sorry for not pushing the right changes. I'd like to take this issue up and fix it.

No problem @NitishKumar06, it was hard to notice that both command where using the same logger (probably it's bad design in our end 🤦‍♂️ ). The simplest solution would be to pass to the logger if it's a deploy or a destroy. We can add it [here](https://github.com/okteto/okteto/blob/master/cmd/build/remote/build.go#L39) and then use that value [here](https://github.com/okteto/okteto/blob/master/pkg/cmd/build/buildkit.go#L283). Let me know if you have any further help and we will help you 😄

**Comment by NitishKumar06** [comment]
> > > @NitishKumar06 my bad, we should show "Deploying..." on `okteto deploy` and "Dstroying..." on `okteto destroy`
> > 
> > 
> > I'm sorry for not pushing the right changes. I'd like to take this issue up and fix it.
> 
> No problem @NitishKumar06, it was hard to notice that both command where using the same logger (probably it's bad design in our end man_facepalming ). The simplest solution would be to pass to the logger if it's a deploy or a destroy. We can add it [here](https://github.com/okteto/okteto/blob/master/cmd/build/remote/build.go#L39) and then use that value [here](https://github.com/okteto/okteto/blob/master/pkg/cmd/build/buildkit.go#L283). Let me know if you have any further help and we will help you smile

- Could you please provide some context how [this function](https://github.com/okteto/okteto/blob/master/cmd/build/remote/build.go#L39) is related to logger? 

- By passing the value [here](https://github.com/okteto/okteto/blob/master/pkg/cmd/build/buildkit.go#L283), do we intend to add a new case?

**Comment by jLopezbarb** [comment]
> * Could you please provide some context how [this function](https://github.com/okteto/okteto/blob/master/cmd/build/remote/build.go#L39) is related to logger?

We run the `deploy/destroy` in a buildkit and this is the struct constructor for all the remote deploy/destroy, but we don't know if it's a deploy or destroy. I found another way of doing it with a better approach. I'll explain it in the next question

> * By passing the value [here](https://github.com/okteto/okteto/blob/master/pkg/cmd/build/buildkit.go#L283), do we intend to add a new case?

Yes we should have two different cases (`deploy` and `destroy`). These values comes from  [this line](https://github.com/okteto/okteto/blob/master/cmd/deploy/remote.go#L151) for deploy and [this other line](https://github.com/okteto/okteto/blob/master/cmd/destroy/remote.go#L149) for destroy. We can change the deploy for destroy in the destroy file, add a new case in the switch(`case "deploy", "destroy":`) and use that for the deploying destroying

**Comment by NitishKumar06** [comment]
> Yes we should have two different cases (`deploy` and `destroy`). These values comes from [this line](https://github.com/okteto/okteto/blob/master/cmd/deploy/remote.go#L151) for deploy and [this other line](https://github.com/okteto/okteto/blob/master/cmd/destroy/remote.go#L149) for destroy. We can change the deploy for destroy in the destroy file, add a new case in the switch(`case "deploy", "destroy":`) and use that for the deploying destroying

Thanks for the help. Here is the new PR: https://github.com/okteto/okteto/pull/3584
cc @pchico83 @AdrianPedriza @jLopezbarb

**Pull request merged**
