### PR TITLE
Skip selector in `okteto down` when only 1 dev container is active

### LINKED ISSUE #3801: okteto down (and up) should automatically select the service when there is only one
When there is only one service present, I don't think there is any value in asking the user to select it. We should automatically select it for them and run the command they requested. 

image

### PR DESCRIPTION
**Pull request by SD-13**
# Proposed changes

Fixes #3801 

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

## How to validate

Please provide step-by-step instructions to replicate your validation scenario. For bug fixes, detail how to reproduce both the bug and its fix, along with any observations.

1. Use a project with multiple services and run `okteto up` on one
1. Stop the session and run `okteto down`
1. Notice how you don't get the prompt with a single service but it automatically deactivates the dev container

## CLI Quality Reminders 🔧

For both authors and reviewers:

- Scrutinize for potential regressions
- Ensure key automated tests are in place
- Build the CLI and test using the validation steps
- Assess Developer Experience impact (log messages, performances, etc)
- If too broad, consider breaking into smaller PRs
- Adhere to our [code style](https://github.com/okteto/okteto/blob/master/docs/code-style.md) and [code review](https://github.com/okteto/okteto/blob/master/docs/code-review.md) guidelines

### CODE REVIEW

**Comment by jLopezbarb** [comment]
Hi @SD-13, Do you know if there is an issue explaining what you are fixing. Can you add a brief description on the changes that you did and why you did them? Changes looks ok to me, but wanted to have it written in case in the future we need to revisit the PR

**Comment by SD-13** [comment]
Hi @jLopezbarb Thanks for checking in. I referenced the issue in the PR description. I am testing the changes locally. Will fill the other fields once it is done. Thanks!

**Comment by jLopezbarb** [comment]
@SD-13 Thanks for doing it. Let us know when the PR is ready and we will review it carefully and check if something is missing. It looks good at first glance 😉

**Review by andreafalzetti — APPROVED** [review]
I've updated the PR title and the "How to validate" section, I've also tested and reviewed the change and it seems to work as expected. Thanks for your contribution 🙏

**Comment by SD-13** [comment]
@jLopezbarb somehow it fell off my radar. Thanks @andreafalzetti for reviewing the PR!

**Review by AdrianPedriza — APPROVED** [review]

**Pull request merged**
