### PR TITLE
Use injected logrus when possible

### PR DESCRIPTION
**Pull request by AgustinRamiroDiaz**
## Proposed changes

- Use the injected logrus instead of referencing the `log` global variable when possible

### CODE REVIEW

**Comment by AgustinRamiroDiaz** [comment]
Related to https://github.com/okteto/okteto/pull/3011

**Comment by ifbyol** [comment]
> Related to #3011

The link points to the PR itself.

What is the motivation of this change? Logger is an important part that is not easy to test and may even impact on how things are being displayed in the UI. Has this generated any issue? Checking the code, I cannot say if `w.out` is always initialized. If that is the case, some of this code could generate a panic at some point and it wouldn't be easy to trace.

As the real problem is having `log` as a global variable. I think this should be handled in its own task all at once. Removing `log` from a global variable and changing the way the logger is initialized and used across all the CLI

**Comment by AgustinRamiroDiaz** [comment]
@ifbyol I've fixed the url.

Yes, the motivation is about removing the `log` global variable. 
You are right that it's a big risk to do this only for a fraction of the change that wouldn't solve the issue

I'll close this in favor of doing it all together

**Comment by ifbyol** [comment]
thanks Agustin!

**Pull request closed without merging**
