### PR TITLE
fix destroy remote when adding envs with blank values

### PR DESCRIPTION
**Pull request by AdrianPedriza**
# Proposed changes
- do not add ENV to img if value is blank

when an image is built for running destroy operations, some tests added an ENV with a blank value so this caused the destroy operation to fail because the image that would execute the command could not be created.

### CODE REVIEW

**Comment by jLopezbarb** [comment]
Should this change be included in the remote deploy too? I guess the issue is affecting also the deployments. What happen if two different pipelines are deployed at the same time?

**Comment by AdrianPedriza** [comment]
> Should this change be included in the remote deploy too? I guess the issue is affecting also the deployments. What happen if two different pipelines are deployed at the same time?

yes, config map updates are also performed in the destroy so it may also be necessary to make use of the `OKTETO_ACTION_NAME` value in the remote deploy. Done 702ae99f7cfec01b8b52c99f13243a1b02517b43

**Review by ifbyol — APPROVED** [review]
We should make sure that the CLI when reads that env variable doesn't treat differently the absence of that env than an empty value

**Comment by AdrianPedriza** [comment]
> We should make sure that the CLI when reads that env variable doesn't treat differently the absence of that env than an empty value

only scenario that does not have this env set was the failing test. Others include this env therefore include its value to the remote

**Review by jLopezbarb — APPROVED** [review]

**Pull request merged**
