### PR TITLE
add forward info to the output

### LINKED ISSUE #227: Show forwarded ports at the end of the "okteto up" execution

### PR DESCRIPTION
**Pull request by rberrelleza**
This fixes #227 

This is how it looks for  a single port:
image

And this is how it looks for multiple ports:
image

### CODE REVIEW

**Comment by rberrelleza** [comment]
@rlamana we could also align the texts, what do you think? (I don't really like it)
image

**Comment by rlamana** [comment]
> @rlamana we could also align the texts, what do you think? (I don't really like it)

I actually like it, but the first port pair should appear on the same line as the label "Forward".

```
   Name:      vote
   Forward:   8090 -> 8090
              8080 -> 8080
```

**Comment by pchico83** [comment]
@rberrelleza if the port cannot be opened, do we show a warning?

**Comment by rberrelleza** [comment]
image
@rlamana thoughts?

**Comment by rlamana** [comment]
> @rlamana thoughts?
It looks perfect to me ;)
Should we place the `name` before the `namespace`?

**Pull request merged**
